name: Build and Push Next.js to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: clantinpro-runner

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ambil Versi dari package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Versi yang mau di-build: $VERSION"

      # Action resmi Docker buat setting Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login ke GHCR otomatis pakai token pipeline
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push persis kayak di laptop lokal
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/clantinpro/${{ github.event.repository.name }}:latest
            ghcr.io/clantinpro/${{ github.event.repository.name }}:${{ env.APP_VERSION }}